analyzer:
  strong-mode:
    implicit-casts: false

  errors:
    missing_return: error
    always_declare_return_types: error
    missing_required_param: error
    unnecessary_new: error

linter:
  rules:
    - avoid_returning_null_for_future